// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fdnfpetdsurzhykppimj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZkbmZwZXRkc3Vyemh5a3BwaW1qIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgwMDM4MzQsImV4cCI6MjA2MzU3OTgzNH0.FQf66jwPO-oTeM6Qb_891RwFs9_ZYMTG5dLg5A9rQcw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);